### ISSUE TITLE
Не работаю ссылки на примеры

### ISSUE THREAD

**Issue by aseven77** [yndx-shri-reviewer/shri-2020-task-1#1]
https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/BASE.md
Внизу есть ссылки на скрины, выдает 404, так же 404 на заглушку

**Comment by yndx-shri-reviewer** [comment]
Поправили. Спасибо!

**Comment by aseven77** [comment]
https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/assets/screenshots/icon-plus.png
330 строка
Тут все еще 404

**Comment by aseven77** [comment]
303 строка

**Comment by yndx-shri-reviewer** [comment]
Добавили. Спасибо!
