### ISSUE TITLE
Значение Брейкпоинта

### ISSUE THREAD

**Issue by Akvy** [yndx-shri-reviewer/shri-2020-task-1#10]
Здравствуйте!

В описании на Гите значение Брейпоинта равно 1024px, а в BASE.md в проекте оно равно 1144px. 

Предполагаю, что это с прошлого раза осталось и не поправили (1144), но все же лучше у вас уточнить какое значение должно быть. Спасибо!

**Comment by yndx-shri-reviewer** [comment]
Да, 1024px. Подскажите, пожалуйста, где остались 1144px? Поиском по проекту найти не получается. Возможно, у вас не совсем актуальная версия проекта? Мы делаем коммиты, если встречаются какие-то ошибки в задании.

**Comment by Akvy** [comment]
Добрый день!

Я там файл указывал в проекте, в котором это попадалось, BASE.md что ли, по
памяти не скажу. В общем там инфа по базовым блокам, как их делать
(продублирована инфа Гита там в общем), но вот боейкпоинт почему-то другой
указан.

Я дома буду поздно сегодня, постараюсь посмотреть и может скриншот
приложить.

А так вообще я его форкнул 36-ым что ли, то есть явно не первым :)

Спасибо!


С уважением,
Андрей Володченко

**Comment by Akvy** [comment]
Как и говорил,

в файле BASE.md указан брейкпоинт 1144px https://prnt.sc/q59df4

**Comment by tensegrity666** [comment]
> Как и говорил, в файле BASE.md указан брейкпоинт 1144px https://prnt.sc/q59df4

Обновите форк, в файле BASE.md очень много всего поменялось.
