### ISSUE TITLE
Переключение тем

### ISSUE THREAD

**Issue by MOTORIST** [yndx-shri-reviewer/shri-2020-task-1#11]
Переключатель onoffswitch должен переключать с темы theme_color_project-default на тему theme_color_project-brand ?

Можно screenshot как это видел дизайнер (страницы с темой theme_color_project-brand) ?

Заранее спасибо!

**Comment by tensegrity666** [comment]
> Переключатель onoffswitch должен переключать с темы theme_color_project-default на тему theme_color_project-brand ?
> 
> Можно screenshot как это видел дизайнер (страницы с темой theme_color_project-brand) ?
> 
> Заранее спасибо!

Очевидно, что на тему invert.
