### ISSUE TITLE
Значение screen-m

### ISSUE THREAD

**Issue by tensegrity666** [yndx-shri-reviewer/shri-2020-task-1#12]
При 1024px (по условию равно брейкпоинту) ширина блока product получается 204.8px

`grid_m-columns_10`
`grid__fraction_m-col_2`
2 колонки по 102.4px

Ширина product по макету 245px. 
При screen-m: 1280px получается нормальная ширина блока.

**Comment by yndx-shri-reviewer** [comment]
Скриншоты макетов делались при ширине браузера 1920px, отсюда и расхождение.
Брейкпойнт 1024px или 1280px влиять на прохождение автотестов не будет.
