### ISSUE TITLE
index.js || script.js

### ISSUE THREAD

**Issue by MOTORIST** [yndx-shri-reviewer/shri-2020-task-1#15]
[Как проверить](https://github.com/yndx-shri-reviewer/shri-2020-task-1#%D0%BA%D0%B0%D0%BA-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%82%D1%8C)
> В каталог build необходимо поместить собранные файлы style.css и index.js.

В задании ниже:
> В корне репозитория должен находиться каталог build с файлами style.css, script.js.

**Comment by mikhin** [comment]
Нужны style.css и script.js.

**Comment by MOTORIST** [comment]
> style.css и script.js.

Спасибо, я в курсе.

**Comment by tensegrity666** [comment]
script.js - скрипт для проверки стилей на шаблонах страниц,
в итоговой сборке должен лежать файл index.js

**Comment by tensegrity666** [comment]
> [Как проверить](https://github.com/yndx-shri-reviewer/shri-2020-task-1#%D0%BA%D0%B0%D0%BA-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%82%D1%8C)
> 
> > В каталог build необходимо поместить собранные файлы style.css и index.js.
> 
> В задании ниже:
> 
> > В корне репозитория должен находиться каталог build с файлами style.css, script.js.


script.js лежит в папке /stub и нужен только для проверки макетов.

в итоговой сборке должен лежать index.js со своими скриптами.

**Comment by yndx-shri-reviewer** [comment]
Поправили. Спасибо!
