### ISSUE TITLE
modules is not defined

### ISSUE THREAD

**Issue by burlaknastia** [yndx-shri-reviewer/shri-2020-task-1#16]
Добрый вечер!

Отправила решение на проверку автотестами, автотесты не прошли с ошибкой "Ошибка шаблонизации: ReferenceError: modules is not defined". 
Подскажите, в чем может быть дело? Локально все собирается, 
modules: ["i-bem-dom__init", "jquery", "next-tick"]. Может script.js должен иметь определенный формат?

**Comment by oreshkin-ay** [comment]
@burlaknastia , привет! А подскажи как отправить решение на проверку автотестами?

**Comment by MOTORIST** [comment]
У Вас script.js скорее всего импортирует внешний модуль (к примеру jquery). Когда запускаются тесты этого модуля нет. В условиях задания все должно быть в одном файле script.js. 

PS еще подсказка, в итоговом файле должно быть только то, что используется в окружении браузера. В Вашем массиве есть точно то, что браузеру не нужно.

**Comment by burlaknastia** [comment]
Если в script.js не использовать i-bem js:
`modules.define('blockName', ['i-bem-dom'], function (provide, bemDom) {etc}`
то тесты проходят. В итоге мы вольны сделать блоки интерактивными как хотим/на свой вкус и цвет? или можно как-то проверить правильность выполнения и этого кода тоже?

**Comment by yndx-shri-reviewer** [comment]
Вам совсем не обязательно использовать i-bem. Мы не навязываем никакие технологии и не ограничиваем вас в них. Приветствуются рациональные и обоснованные решения.
Что касается проверки кода, то, поскольку его объем очень маленький в данном задании, правильность его работы проверяется ручным тестированием.
Если интерактивные элементы работают так, как описано в задании, значит, код работает правильно.

**Comment by burlaknastia** [comment]
Спасибо!
