### ISSUE TITLE
Автотесты

### ISSUE THREAD

**Issue by oreshkin-ay** [yndx-shri-reviewer/shri-2020-task-1#18]
День добрый! 
А поправлены ли значения ширины экрана в автотестах? По скринам все сходится, но автотесты ругаются. Или дело не в ширине?
![image](https://user-images.githubusercontent.com/17002069/70386103-3bfe2b80-19a6-11ea-8e37-e7bbf3be4098.png)

![image](https://user-images.githubusercontent.com/17002069/70386096-0ce7ba00-19a6-11ea-9909-f9a6c1a5fb7f.png)

**Comment by vodolazskikh** [comment]
Как решилось?

**Comment by oreshkin-ay** [comment]
Привет. Дело было не в ширине. Другие блоки не совпадали с макетами.

**Comment by oreshkin-ay** [comment]
https://github.com/yndx-shri-reviewer/shri-2020-task-1/issues/20
@vodolazskikh "есть ветки с результатами автотестов"

**Comment by vodolazskikh** [comment]
@oreshkin-ay Офигеть, и ведь нигде ни слова об этом) спасибо)
