### ISSUE TITLE
Автотесты

### ISSUE THREAD

**Issue by oreshkin-ay** [yndx-shri-reviewer/shri-2020-task-1#20]
Сделал для проверки наложение Ваших скринов, получил вот такой результат.
Есть расхождения в полпикселя- белые полоски/зазоры. Учитывается ли это в автотестах, и если нет, почему они не проходят? А если да, то возможен ли какой-то лог ошибок?
![image](https://user-images.githubusercontent.com/17002069/70387426-49231680-19b6-11ea-9af4-db47d3c0e345.png)
![image](https://user-images.githubusercontent.com/17002069/70387466-648e2180-19b6-11ea-9c1c-17ebec5426cd.png)

**Comment by MOTORIST** [comment]
У меня пиксель в пиксель. Скорее всего в тестах стоит один в один.

**Comment by oreshkin-ay** [comment]
Так у тебя прошли для десктопа и таких полпикселя как у меня нет?

**Comment by oreshkin-ay** [comment]
![image](https://user-images.githubusercontent.com/17002069/70387591-fe0a0300-19b7-11ea-8dc9-324b81a15343.png)

**Comment by MOTORIST** [comment]
> Так у тебя прошли для десктопа и таких полпикселя как у меня нет?

И для дектопа и для мобильной версии. Один в один, не отличить.
Отправь проект на тесты, покажет (подсветит) ошибки.

**Comment by oreshkin-ay** [comment]
![image](https://user-images.githubusercontent.com/17002069/70388029-99ea3d80-19bd-11ea-8e76-c2cafe65ee65.png)
Не пойму что значат ошибки, по скринам 1 в 1

**Comment by tensegrity666** [comment]
Для мобильной версии ведь нет макета, какой там может быть пиксельперфект?

**Comment by oreshkin-ay** [comment]
Макетов нет, в том то и дело, как проверять?

**Comment by playhardgopro** [comment]
@oreshkin-ay у тебя в форке 1 таска есть ветки с результатами автотестов, открой да посмотри, что не так. Слева твой вариант, справа - что должно получиться.

**Comment by oreshkin-ay** [comment]
@playhardgopro можешь подробнее написать, не найду где это

**Comment by oreshkin-ay** [comment]
нашел, спасибо

**Comment by playhardgopro** [comment]
@oreshkin-ay да не за что)

**Comment by oreshkin-ay** [comment]
@playhardgopro а где про это было написано? может я еще что-то не знаю)
