### ISSUE TITLE
Замечание по макету или верстке.

### ISSUE THREAD

**Issue by MOTORIST** [yndx-shri-reviewer/shri-2020-task-1#21]
У меня упали тесты при мобильном разрешении, стояли отступы справа и слева на контейнере (layout__container ). Они стояли для того чтобы контент при мобильно разрешении не прилипал к краям.
В эталонном screenshot текст липнет к viewport, что с точки usability не правильно. Также липнет рамка продуктов, что с точки зрения дизайна не очень.

**Comment by oreshkin-ay** [comment]
@MOTORIST привет. А не десктопной прошли?

**Comment by yndx-shri-reviewer** [comment]
Вы правы, хорошее и логичное замечание. Но задание уже опубликовано, и если сейчас начать менять макеты, это повлияет на большое количество людей, поэтому выполните его, пожалуйста, в точном соответствии с теми условиями, что есть сейчас.
