### ISSUE TITLE
Результаты автотестов

### ISSUE THREAD

**Issue by tensegrity666** [yndx-shri-reviewer/shri-2020-task-1#23]
> Если интерактивные элементы работают так, как описано в задании, значит, код работает правильно.

Извините, есть несколько вещей, которые мне непонятны.

- Логи автотестов. Например, фрагмент:

``Ошибка шаблонизации: TypeError: Cannot set property 'onload' of null
  at eval (webpack-internal:///./static/tensegrity666/script.js:3:22)
  at Object../static/tensegrity666/script.js (file:///opt/buildagent/work/e163812401825360/screenshots/static/tensegrity666/build/script.js:96:1)``

По такому логу я не могу даже предположить, где ошибка.  
Скрипт работает (он длиной 30 строк, а ошибки указаны на 96, 87 и тд) , есть расхождения по вёрстке, но я не понимаю, тратить ли время на устранение расхождений в несколько пикселей, или всё вообще сделано неправильно и время тратить не стоит. Или скрипты должны быть не так написаны.

- Критерии "Мобильная версия". В задании есть только ширина и условие, что блоки перестраиваются друг под друга. Некоторые блоки могут располагаться по-разному, блоки Product, например. 

- Если использованы не все классы из шаблонов страниц - это ошибка или нет?

**Comment by yndx-shri-reviewer** [comment]
> Cannot set property 'onload' of null

У вас onload используется только в одном месте. Подумайте, в каких случаях такая ошибка может возникнуть, и как написать скрипт таким образом, чтобы он не падал.

> Некоторые блоки могут располагаться по-разному, блоки Product, например

Когда вы почините ошибки JS, то на скриншотах сможете увидеть расхождения в мобильной версии и поправить их, если таковые появятся.

> Если использованы не все классы из шаблонов страниц - это ошибка или нет?

Мы приветствуем любые обоснованные решения. Если вы уверены, что какие-то классы вам не нужны, и лучше сделать по-другому, то делайте так, как считаете нужным. Только оставьте, пожалуйста, соответствующие комментарии в README.md.

**Comment by tensegrity666** [comment]
Спасибо!
