### ISSUE TITLE
Вертикальные отступы у текстовых блоков

### ISSUE THREAD

**Issue by mpoliakov** [yndx-shri-reviewer/shri-2020-task-1#24]
В описании не указаны вертикальные отступы у текстовых блоков (text/word), судя по скриншотам они явно есть.

**Comment by yndx-shri-reviewer** [comment]
Вместо вертикальных отступов мы указывали междустрочный интервал.

**Comment by rakov-di** [comment]
А важно ли, каким именно образом задавать этот интервал? Например, как отступ снизу, отступ сверху или с обеих сторон? И задавать ли его общему блоку text или отдельным элементам text__word? Или это на наше усмотрение и главное, чтоб совпало со скриншотами [index](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/assets/pages/index.png) и [product](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/assets/pages/product.png)?

**Comment by yndx-shri-reviewer** [comment]
> Или это на наше усмотрение и главное, чтоб совпало со скриншотами index и product?

Абсолютно верно. Мы не ограничиваем вас в выборе вариантов реализации.
