### ISSUE TITLE
Блок payment

### ISSUE THREAD

**Issue by Glazomer** [yndx-shri-reviewer/shri-2020-task-1#26]
В "подробная спецификация блоков с подсказками" написано что блок payment__header имеет стили form__item_space-v_l что равно 24px сверху и снизу, но на макете внутренний отступ сверху в payment__header равен 32px а снизу 38px. Такие величины никак не получить примиксовая   данные блоки паттернов в блоке .payment.
(https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/assets/screenshots/payment.png)

**Comment by yndx-shri-reviewer** [comment]
В задании ошибки нет. Доп. отступы сверху и снизу вы получаете за счет блока text.

**Comment by Glazomer** [comment]
> В задании ошибки нет. Доп. отступы сверху и снизу вы получаете за счет блока text.

Единственные отступы у блока text это text_type , но о них ничего не сказано, а так же ни подходит ни одно значение.
Если на text примиксовать form__item то отступы все-равно не будут правильные

**Comment by yndx-shri-reviewer** [comment]
Для блока text задан междустрочный интервал, который больше размера шрифта, и он будет влиять на высоту блока и давать визуально дополнительные отступы.

**Comment by Glazomer** [comment]
> Для блока text задан междустрочный интервал, который больше размера шрифта, и он будет влиять на высоту блока и давать визуально дополнительные отступы.

38px интервал - 16px размер шрифта = 22px, 8 сверху 14 снизу — ВСЕ СХОДИТСЯ
СПАСИБО!)

edit: typo
