### ISSUE TITLE
Должен ли переключатель onoffswitch быть интерактивным? 

### ISSUE THREAD

**Issue by rakov-di** [yndx-shri-reviewer/shri-2020-task-1#27]
Должен ли переключатель onoffswitch быть интерактивным? 
Если да, то:

1. между какими темами он должен переключаться на странице index и product? Ведь тем у нас 4.
2. какое изображение (из блока image) должно применяться к теме theme_color_project-warning (в ТЗ указано для всех тем, кроме этой).

**Comment by yndx-shri-reviewer** [comment]
> между какими темами он должен переключаться на странице index и product? Ведь тем у нас 4.

Переключение осуществляется только между дефолтной и инверсной темами. Блоки с другими темами остаются без изменения.

> какое изображение (из блока image) должно применяться к теме theme_color_project-warning (в ТЗ указано для всех тем, кроме этой).

В задании нет блоков с изображениями, имеющих тему project-warning
