### ISSUE TITLE
Существует ли для модификатора card__content_space-a значение xxl?

### ISSUE THREAD

**Issue by rakov-di** [yndx-shri-reviewer/shri-2020-task-1#28]
В ТЗ в описании модификатора card__content_space-a перечислены только 4 значения: m, xl, l, xxxl. Т.е. значение **xxl** отсутствует. 
Но в блоке Cover в [подробной спецификации](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/CONTENT.md#%D1%81%D0%BC%D1%8B%D1%81%D0%BB%D0%BE%D0%B2%D0%BE%D0%B9-%D0%B1%D0%BB%D0%BE%D0%BA-cover) и в примере страницы [product.json](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/stub/pages/product.json) он есть: **card__content_space-a_xxl**. 
Это опечатка? Нужно добавить этот модификатор в стилях или заменить его на xxxl в верстке product.json?

**Comment by yndx-shri-reviewer** [comment]
Добавили значение **xxl** для модификатора **card__content_space-a**. Спасибо!
