### ISSUE TITLE
Могут ли стили для Базовых блоков содержать дополнительные свойства (не указанные в ТЗ)?

### ISSUE THREAD

**Issue by rakov-di** [yndx-shri-reviewer/shri-2020-task-1#29]
Могут ли стили для **[базовых блоков](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/BASE.md)** содержать дополнительные свойства (не указанные в ТЗ)?
Например, на [скриншоте для product](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/assets/pages/product.png) у списка карточек имеется черный фон, который как будто бы нельзя сделать, не добавляя дополнительных стилей (не указанных в ТЗ) для блока [section](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/BASE.md#%D0%B1%D0%BB%D0%BE%D0%BA-section) или [layout__container](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/BASE.md#%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82-container)? 

Или это проблема конкретно моих неверных стилей и нужно обходиться только стилями, явно указанными в ТЗ?

И обратный вопрос:
Могут ли стили для **[контентных блоков](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/CONTENT.md)** **НЕ** содержать дополнительные свойства?

Из ТЗ:

> “блок должен содержать собственные уникальные дополнительные стили”.

Прям “должен”?

**Comment by yndx-shri-reviewer** [comment]
Дизайн-система и дизайн задания построены таким образом, чтобы вам требовалось писать минимальное количество стилей для контентных блоков. Для них, как правило, нужно писать стили в рамках требований, указанных в разделе **исходные стили** в описании блока.

Контентные блоки могут и не содержать дополнительных свойств, это нормально.

Если вы считаете нужным добавить какие-то стили в базовые блоки, добавляйте. Мы не ограничиваем вас в этом. Мы за любые обоснованные решения, только оставьте комментарий в README.md на этот счет.
