### ISSUE TITLE
Размеры шрифтов контентных блоков

### ISSUE THREAD

**Issue by Vorovalnitsev** [yndx-shri-reviewer/shri-2020-task-1#3]
Блок Product 
Имя: l Подпись: m

Вложенные контентные блоки:
text text_view_primary text_size_m,
text text_view_primary text_size_s,

Согласно таблице ниже высота слов должна быть 7px и 8px. На сриншоте к блоку product 8px и 10px. На блоках warning и payment подобные проблемы с высотой слов. Остальные блоки не успел проверить. 

Размерный модификатор блока text | Значение высоты элемента word
--------------------------------------- | -----------------------------------
s | 7px
m | 8px

**Comment by yndx-shri-reviewer** [comment]
Поправили описание. Спасибо!
