### ISSUE TITLE
Межстрочный интервал

### ISSUE THREAD

**Issue by Glazomer** [yndx-shri-reviewer/shri-2020-task-1#30]
В .product__header различаются отступы от текста сверху (38px) и снизу(32px). Хотя у всех модификаторов элементов отступы сверху и снизу симметричны (35px). Как такое возможно? Что делать перфекционистам?

**Comment by yndx-shri-reviewer** [comment]
А на какой странице вы нашли product__header?

**Comment by Glazomer** [comment]
Простите, я имел ввиду payment__header

> А на какой странице вы нашли product__header?

**Comment by yndx-shri-reviewer** [comment]
Часть отступов у вас берется за счет модификатора space-v_l (24 px), а другая часть -- за счет соотношения междустрочного интервала и размера текста для text_size_xxl.

**Comment by Glazomer** [comment]
> Часть отступов у вас берется за счет модификатора space-v_l (24 px), а другая часть -- за счет соотношения междустрочного интервала и размера текста для text_size_xxl.

Да, я это понимаю, но строчный интервал 38px, текст – 16px, остается 22px.
Теперь суть вопроса, как распределяются эти 22px? Если 11 сверху и 11 снизу, получается 24+11 = 35px сверху и снизу, а на макете 38px сверху и 32px снизу

**Comment by nat-k-dev** [comment]
+1 к вопросу про payment__header. 
Также в блоке payment видно, что текстовые блоки в lable размещены по центру по вертикали, поэтому межстрочный интервал нужно делить пополам, для верха и низа. А в блоке с текстами (макет product.png, верхний правый отсек) нижняя строка лежит на границе блока, из чего следует, что межстрочный интервал не надо делить пополам, он полностью лежит над строкой с текстом. 
Получается, что межстрочные интервалы не универсальны, для разных блоков они по разному вычисляются. Так и задумано?

**Comment by yndx-shri-reviewer** [comment]
> Также в блоке payment видно, что текстовые блоки в lable размещены по центру по вертикали, поэтому межстрочный интервал нужно делить пополам, для верха и низа.

У вас в задании не указано, что отступы должны быть распределены равномерно.
Для этого размера шрифта и междустрочного интервала они получились одинаковыми сверху и снизу, но в общем случае они таковыми оставаться не должны. В условии заданы только междустрочный интервал и высота текста, и вам нужно задать их по возможности наиболее простым способом.

**Comment by Glazomer** [comment]
> > Также в блоке payment видно, что текстовые блоки в lable размещены по центру по вертикали, поэтому межстрочный интервал нужно делить пополам, для верха и низа.
> 
> У вас в задании не указано, что отступы должны быть распределены равномерно.
> Для этого размера шрифта и междустрочного интервала они получились одинаковыми сверху и снизу, но в общем случае они таковыми оставаться не должны. В условии заданы только междустрочный интервал и высота текста, и вам нужно задать их по возможности наиболее простым способом.

А как тогда распределять интервал!? Зачем вы так размазываете задание? Надо ли добавлять какие-нибудь дополнительные модификаторы?! Или это прикрутить к стилям payment__header?

**Comment by yndx-shri-reviewer** [comment]
> Зачем вы так размазываете задание?

Потому что нам важно увидеть, как кандидат действует в ситуации, когда есть макет, есть несколько вариантов решения, и нужно выбрать оптимальный.
Возможно, вы выбрали не самый лучший способ реализации блока text. Проверьте на других блоках, в т.ч. на странице product.

> Надо ли добавлять какие-нибудь дополнительные модификаторы?!

Нет. Модификаторов, которые указаны в описании блоков достаточно. Вы можете сверяться с BEMJSON'ами страниц. Они же используются в инфраструктуре тестирования.
