### ISSUE TITLE
Прилипает шапка при автотестах

### ISSUE THREAD

**Issue by kohanvl** [yndx-shri-reviewer/shri-2020-task-1#31]
При тестировании верстки страницы **index.html** на локальной машине в каталоге /stub/ и при сверке через pixel perfect, все проходит хорошо.
**_Вот, как выглядит верстка на локалке https://imgur.com/a/l69z1cM_**

При отправки на автотесты, появляется проблема прилипающего хедера, хотя все отступы точно есть. Вставлял даже несколько отступов, которые перекрывают друг друга, допуска то, что какие-нибудь из них затираются.
**_Вот, как выглядит верстка при краше автотестов https://imgur.com/a/C49v0HG, где левый скрин - моя верстка и правый - эталонная верстка._**

В чем может быть проблема? Не могут ли тесты случайно затирать какой-либо класс или отступы?

**Comment by yndx-shri-reviewer** [comment]
Автотесты ничего не затирают. Скорее всего, ошибки в стилях блока header.

**Comment by kohanvl** [comment]
Проблема решилась заменой margin на padding.
