### ISSUE TITLE
Ошибка шаблонизации, отсутствующие блоки: cover

### ISSUE THREAD

**Issue by ladanovn** [yndx-shri-reviewer/shri-2020-task-1#33]
Автотест возвращает следующую ошибку:
![image](https://user-images.githubusercontent.com/30371613/71081166-bc3f4080-219f-11ea-9ad2-9ee27d9a82c8.png)

Но в собранном style.css определенно есть этот блок. 
![image](https://user-images.githubusercontent.com/30371613/71081428-37a0f200-21a0-11ea-8e06-3f6faa358c0f.png)

Может быть я чего-то не понимаю ?

**Comment by yndx-shri-reviewer** [comment]
Вы рендерите свое реакт-приложение на body. При этом вы не знаете, каким образом и, самое главное, когда генерится HTML-разметка в наших автотестах и с какими параметрами в URL'е запускаются наши автотесты.
Какое поведение от своего приложения в этой ситуации вы ожидаете?

**Comment by ladanovn** [comment]
Спасибо за ответ!
