### ISSUE TITLE
Путь до картинок

### ISSUE THREAD

**Issue by mpoliakov** [yndx-shri-reviewer/shri-2020-task-1#34]
Подскажите, какой путь до картинок (image-placeholder-inverse.svg, image-placeholder-primary.svg) при запуске тестов? Я копирую картинки в папку build, но на скриншотах они не отображаются.

**Comment by yndx-shri-reviewer** [comment]
Мы не подтягиваем в автотесты никаких файлов кроме скриптов и стилей, в т.ч. *.svg.

**Comment by KSGitUser** [comment]
Речь о том что нечего не потягивают, однако автотесты не проходят, на автотестах нет картинок, а на локалном есть

https://drive.google.com/file/d/1kAtFrg1cX-ls1N18kmMoOcshsBXBOxni/view?usp=sharing
