### ISSUE TITLE
Стандартная высота блока

### ISSUE THREAD

**Issue by bristl** [yndx-shri-reviewer/shri-2020-task-1#35]
В трансляции говорили, что у блоков задается дефолтная высота.
А конкретно в вопросе про блок **card**.

Ни где в описании к блоку или выше не могу это найти, подскажите, где это указано?

**Comment by yndx-shri-reviewer** [comment]
Блок card -- это блок из слоя паттернов. Он задает исключительно структуру, но не определяет размеры.
Горизонтальные размеры контентных блоков задаются сеткой, вертикальные -- стилями самих контентных блоков.
