### ISSUE TITLE
Горизонтальный отступ у layout, header, footer

### ISSUE THREAD

**Issue by nat-k-dev** [yndx-shri-reviewer/shri-2020-task-1#36]
На странице описания контентных блоков заданы горизонтальные отступы у блоков .header и .footer : "значения вертикальных отступов: xxxl — вертикальный, --gap горизонтальный;".

У блока layout горизонтальные отступы не указаны. 

В результате, на узких экранах содержимое layout прилегает к краю экрана, а у header и footer отступы. Как следствие, левая вертикальная граница header и footer лежит не на одной линии с границами блоков внутри layout. 

Так и задумано? 
Или на всех экранах левые и правые вертикальные границы header, layout, footer должны идти по одной линии?

![issue-отступы](https://user-images.githubusercontent.com/8708553/71234558-78b51580-230a-11ea-91d7-8f5b1c2ef818.jpg)

**Comment by tensegrity666** [comment]
> Так и задумано?

Без этих отступов автотесты не пройдут.

**Comment by nat-k-dev** [comment]
То что автотесты не пройдут без отступов у header и footer, это ожидаемо, потому что об этом в задании явно сказано.
Но про горизонтальные отступы у layout ничего не сказано. И так как макет есть только для широкого экрана, то не совсем понятно, как должны выглядеть левые и правые границы на узких экранах. В одну линию, как и при больших разрешениях, или границы header/footer с отступами, а границы layout примыкают к краю браузера?

**Comment by tensegrity666** [comment]
> не совсем понятно, как должны выглядеть левые и правые границы на узких экранах.

Они должны выглядеть так, как на скриншоте. Ширина 15px.

**Comment by nat-k-dev** [comment]
Спасибо
