### ISSUE TITLE
Блок text. Отступы.

### ISSUE THREAD

**Issue by victor-kugay** [yndx-shri-reviewer/shri-2020-task-1#37]
Добрый день. 

К сожалению я не смог найти описание отступов между строками текста. Присутствует width, height, даже margin для соответствующих типов текста, однако, такой важной характеристики, как отступы нет. 

Возможно это стандартный 1.5 отступ или flex контейнер с space-between выравниванием контента? 

Буду благодарен за комментарий.

**Comment by playhardgopro** [comment]
межстрочные интервалы заданы

**Comment by 57Viktor57** [comment]
Вы имеете ввиду отступы для типов текста. В проекте очень много текстов без указания типа. В таком случае они должны иметь отступы, аналогичные text_type_p?

**Comment by victor-kugay** [comment]
Извиняюсь, вижу. Отступы указаны)
