### ISSUE TITLE
Размерная линейка

### ISSUE THREAD

**Issue by playhardgopro** [yndx-shri-reviewer/shri-2020-task-1#4]
На скриншоте размеры отступов отличаются от заданных. Проверка автотестами фэйлится.
Пожалуйста, уточните размеры отступов из данного пункта:

> Модификации отступов
> 
> Нужно написать модификатор на отступы, содержащий все переменные, которые используются для отбивки элементов и блоков внутри смысловых сущностей и каркасных конструкций.
> 
> .theme_space_default — дефолтная размерная линейка.
> 
> Пример размеров текста:
> - xxxs: 2px;
> - xxs: 4px;
> - xs: 8px;
> - s: 12px;
> - m: 16px;
> - l: 20px;
> - xl: 24px;
> - xxl: 32px;
> - xxxl: 40px;
> - xxxxl: 48px;
> - xxxxxl: 72px.

**Comment by yndx-shri-reviewer** [comment]
Спасибо за замечание! Поправили значения в условии.

**Comment by playhardgopro** [comment]
@yndx-shri-reviewer Спасибо, но все равно что-то не так :)
Очень похоже, что в десктопной версии `--gap` должен быть `xl`, а не `xxxl`.

>  Отступы в сетке
> 
> .theme_gap_small — модификатор на отступ между колонками и отступами в сетке. В стилях содержит переменную gap, которая на десктопе имеет значение, соответствующее **xxxl-отступу**, а в мобильном представлении m. Для получения половинного значения переменная gap делится на два.

**Comment by yndx-shri-reviewer** [comment]
Да, вы правы. xl в десктопном, s в мобильном представлении. Поправили в условии. Спасибо!

**Comment by oreshkin-ay** [comment]
@playhardgopro у тебя прошли автотесты с новыми значениями?
