### ISSUE TITLE
Блок history. Отступы

### ISSUE THREAD

**Issue by Yubil-Olga** [yndx-shri-reviewer/shri-2020-task-1#40]
В задании указано, что элементу show блока history нужно установить внешний отступ сверху m. Но отступ в этом месте, если ориентироваться на скриншоты, кажется лишним. Это опечатка?

**Comment by yndx-shri-reviewer** [comment]
Нет, опечатки там нет. Этот модификатор должен там быть, и при этом верстка должна соответствовать скриншотам макетов.
