### ISSUE TITLE
Сетка на скриншоте.

### ISSUE THREAD

**Issue by newyorrker** [yndx-shri-reviewer/shri-2020-task-1#41]
Возник один вопрос. Мне никак не дает покоя, что на скриншоте одна колонка равна 626px а другая 627px, `grid__fraction_m-col_5` и `grid__fraction_m-col_5` соответственно – это для десяти-колоночной сетки `grid_m-columns_10`. 
У меня в браузере обе колонки по 626,5px, интересно какая допустимая погрешность в тестах?

**Comment by yndx-shri-reviewer** [comment]
Во-первых, 0.5px -- вещь достаточно абстрактная. На скриншотах и при отображении на мониторе, как вы уже заметили, эти 0.5px округляются в ту или иную сторону.
Во-вторых, у нас всё равно стоит небольшой допустимый процент погрешности, и очень маловероятно, что разница в 1px завалит прохождение тестов.

Если вдруг такое случится, напишите нам, пожалуйста.
