### ISSUE TITLE
Блок History > list_item

### ISSUE THREAD

**Issue by ghost** [yndx-shri-reviewer/shri-2020-task-1#42]
Всем привет. Подскажите пожалуйста, в stub, в папке pages есть Index.bemjson файл. Соответственно при генерации его, в html у нас появляется в разметке:

1. блок **history** (с примиксованным блоком **list**);
2. в **history** вложен элемент **history__transaction**. К нему примиксован элемент **list__tem**  с примиксованным модификатором **list__item_space-a_m**). Отсюда получаем внутренние отступы 18px.;
3. в **history__transaction** вложена видимая часть нашего бутерброда **history__show**, к которому примиксован элемент **list__item** с модификатором **list__item_indent-t_m**. Получаем еще внешний отступ сверху в 18px. .

В результате получаем отступ видимой части **history__show** от верхнего края в 36px, что дает не соответствие scrinshoot'у [history ](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/assets/screenshots/history.png).

![2019-12-25_06-12-19](https://user-images.githubusercontent.com/33181633/71431592-f058bb00-26e3-11ea-9938-5ce56f826bf3.png)
![2019-12-25_06-14-17](https://user-images.githubusercontent.com/33181633/71431598-fd75aa00-26e3-11ea-8be0-cebeb823c805.png)

Это так и должно быть? Или же необходимо использовать собственные стили к элементу history__show блока history? Или же я где-то ошибаюсь?

**Comment by yndx-shri-reviewer** [comment]
Так и должно быть. Ни в скриншотах, ни в BEMJSON'е ошибки нет. 

> Или же необходимо использовать собственные стили к элементу history__show блока history?

Это уже на ваше усмотрение, мы не комментируем детали реализации
