### ISSUE TITLE
Результат

### ISSUE THREAD

**Issue by Yubil-Olga** [yndx-shri-reviewer/shri-2020-task-1#43]
В корне репозитория должен находиться каталог build с файлами style.css, script.js. 
Для каждой страницы в каталоге build следует создать свою папку с соответствующими style.css и script.js?

**Comment by MOTORIST** [comment]
В корне должна быть одна папка build c двумя файлами style.css, script.js.

**Comment by yndx-shri-reviewer** [comment]
> В корне репозитория должен находиться каталог build с файлами style.css, script.js.
> Для каждой страницы в каталоге build следует создать свою папку с соответствующими style.css и script.js?

У вас общие стили и скрипты для двух страниц
