### ISSUE TITLE
Переключение темы блоков

### ISSUE THREAD

**Issue by burlaknastia** [yndx-shri-reviewer/shri-2020-task-1#45]
Добрый вечер!

В задании указано, что переключение тем осуществляется между `project-default` и `project-inverse`. Но есть некоторые блоки, как `event` на странице `index` и блок с карточками продуктов на странице `product`, тема которых задана заранее (`inverse`). Так, если переключить тему страницы `index` на `inverse`, то фон блока `event` станет белым, что выглядит странным при черном фоне остальных блоков (кроме `warning`). 

Вопрос - нужно ли менять темы этих блоков при нажатии на переключатель?

**Comment by yndx-shri-reviewer** [comment]
Нужно. Темы переключаются глобально для всех блоков страницы. Иначе, как вы правильно заметили, отображение будет получаться очень странным.
