### ISSUE TITLE
URL изображений

### ISSUE THREAD

**Issue by mikhin** [yndx-shri-reviewer/shri-2020-task-1#5]
Здравствуйте. Подскажите, по какому URL доступны изображения? По адресам `/images/image-placeholder-inverse.svg` и `/assets/images/image-placeholder-inverse.svg` изображения во время автотестов не доступны.

**Comment by yndx-shri-reviewer** [comment]
Автотесты скачивают только js и css, *.svg-файлы в автотестах не используются.

**Comment by mikhin** [comment]
Спасибо!
