### ISSUE TITLE
Различия в отображении от автотестов

### ISSUE THREAD

**Issue by quager** [yndx-shri-reviewer/shri-2020-task-1#54]
При разработке проверяю в нескольких браузерах, размеры совпадают с эталонным из папки assets. Но когда проходят автотесты в изображениях совершенно другие размеры. Например блок warning имеет ширину 409px, а по результатам автотестов в моём блоке ширина 418px. Подскажите из-за чего так может происходить?

**Comment by yndx-shri-reviewer** [comment]
Проверьте вашу реализацию блока grid. Именно он задает ширину ваших блоков.
