### ISSUE TITLE
Ширина страницы screen-m

### ISSUE THREAD

**Issue by bemdev** [yndx-shri-reviewer/shri-2020-task-1#55]
Приветствую. Не проходят тесты

![Снимок экрана 2020-01-07 в 19 41 03](https://user-images.githubusercontent.com/20998840/71907619-d27c6300-3185-11ea-94b3-121622d8c67e.png)

Судя по всему это актуальный провал тестов. У меня вопрос.

Есть брейкпоинт 1024px при нем все блоки должны перестроиться друг под друга. Все так и сделано. Но кажется что то не так делаю.

Ширина страница screen-m это какая то переменная которая указывает ширину для блоков layout и grid ? не вижу в дереве вообще использование такого модификатора. или явного указания где то используется.

Помогите советом, куда смотреть. Написаны тесты ко всем блокам и они проходят с небольшим трешхолдом. Но при сдачи на автотесты все валится (

Просмотрел скриншоты после Ваших тестов, и такое чувство что картинки которые даны как эталон не совсем те или я делаю что то не так ,(

Возможно Вы мне скажите, что трешхолд 0.01 и мне исправить помарки.

Так же хотелось бы отметить, что я добавил стилей для красивого и правильного отображения блоков в мобильной отображении, и смотрю иногда это и является проблемой...

**Comment by stas-laniuk** [comment]
> Ширина страница screen-m это какая то переменная которая указывает ширину для блоков layout и grid ? 

Нет, это величина, которая определяет на какой ширине вьюпорта поведение блоков изменится. Меньше 1024p - блоки строятся для отображения на мобильном устройстве, больше или равно 1024px - блоки строятся для отображения на десктопе.

Трешхолд однозначно не меньше пикселя, скорее всего - больше.

> Просмотрел скриншоты после Ваших тестов, и такое чувство что картинки которые даны как эталон не совсем те или я делаю что то не так ,(

Скриншоты представляют собой три изображения, "склеенных" вместе. Левая треть - ваша верстка, центральная треть - наложение вашей верстки на эталонную, правая треть - эталон.

> Так же хотелось бы отметить, что я добавил стилей для красивого и правильного отображения блоков в мобильной отображении, и смотрю иногда это и является проблемой...

А от такой самодеятельности лучше отказаться. Сделайте так, как требует задание (даже если в задании где-то что-то не совсем правильно с точки зрения дизайна и UX).

**Comment by bemdev** [comment]
![index_desktop](https://user-images.githubusercontent.com/20998840/71993356-63b80c00-3250-11ea-9345-8d82a8fea9dc.png)

такая погрешность фатальна?

И может быть, что тесты как то залипают. Страница product была переделана, но скришот приходит старый. Причем как видно ранее я делал соответсвенно эталонному изображению из assets

![product_desktop](https://user-images.githubusercontent.com/20998840/71993507-a7127a80-3250-11ea-97cf-b5f2e5956e53.png)

Специально еще раз проверил, что происходит локально. И так делается как в левой части.

**Comment by stas-laniuk** [comment]
Если бы тесты залипали, по этой теме был бы не только ваш комментарий. Что касается фатальности погрешности, уверен, что отсутствие изображений-заглушек фатально.  Думаю, как добьетесь их отображения, страница `index` у вас автотест пройдет.

**Comment by bemdev** [comment]
> Если бы тесты залипали, по этой теме был бы не только ваш комментарий. Что касается фатальности погрешности, уверен, что отсутствие изображений-заглушек фатально. Думаю, как добьетесь их отображения, страница `index` у вас автотест пройдет.

На сколько мне известно, картинки не будут загружены при тестах. 
https://github.com/yndx-shri-reviewer/shri-2020-task-1/issues/34

Есть подозрение, что это очень общее описание провалов тестов. И проблему стоит искать в любых не совпадениях. Хотя кому то удалось, пройти быстро.

Вообщем интересно очень делать задание которые видоизменяется "когда захочется". 

..и по секрету во втором задании куда приятнее лог ошибок.

**Comment by yndx-shri-reviewer** [comment]
> такая погрешность фатальна?

Если автотесты не проходят, то да. И судя по тому, что красным выделены все блоки с текстом, проблема, скорее всего, именно в нём.

> И может быть, что тесты как то залипают. Страница product была переделана, но скришот приходит старый.

Мы при каждом запуске тестов берем последнюю версию мастера. Скорее всего, вы не сделали пуш в удаленный репозиторий перед запуском автотестов.

> Возможно Вы мне скажите, что трешхолд 0.01 и мне исправить помарки.

Трешхолд как раз равен 0.01

**Comment by bemdev** [comment]
> Мы при каждом запуске тестов берем последнюю версию мастера. Скорее всего, вы не сделали пуш в удаленный репозиторий перед запуском автотестов.

Странно. И лыжи не едут.

Создал новый репозиторий клонирую с гита запускаю, все хорошо. Картинки отключены, страница product отрисовывается правильно.

Запускаю Ваши тесты по новой ссылке, результат падает, что и картинки есть и страница product имеет другой вид вплоть до json дерева возможно.

![product_desktop (1)](https://user-images.githubusercontent.com/20998840/72135804-c15b6e00-33a0-11ea-83a8-92e930b7094a.png)

![index_desktop_block_product](https://user-images.githubusercontent.com/20998840/72135825-cb7d6c80-33a0-11ea-9406-a9268de7451a.png)

В папке build лежит два файла и папка для картинок
В папке pages лежат json файлы как в примере stub

Остальное разложено иначе чем в классическом форке, но есть assets папка где лежит и json и скриншоты, которые считались эталонными для локальных тестов. это же какая разница вроде.

Что можно сделать?

Если проблема решиться до ответа, то и ишью закрою.
