### ISSUE TITLE
автотесты для script.js ?

### ISSUE THREAD

**Issue by stas-laniuk** [yndx-shri-reviewer/shri-2020-task-1#56]
Здравствуйте. Написал стилей, написал скриптов, собрал кое-как вебпаком. 
Локально все работает. 
Скачиваю из репозитория, устанавливаю, собираю, проверяю через папку stub - работает.

Отправляю на автотесты - не проходит. Когда еще не писал script.js и проверял автотестами вертску, в build помещал пустой script.js - всё с автотестами было ок. Причина, как я понимаю, в моем script.js. Судя по количеству пунктов в error log, я что-то делаю принципиально неправильно.  
![Screenshot_2020-01-08 https account shri yandex](https://user-images.githubusercontent.com/50028051/71965127-216eda80-3210-11ea-84c1-c230b7e81f77.png)

**Comment by bemdev** [comment]
В данном случае вебпак скорее излишне. Так как js кода там 45 строк, а стили мне кажется можно собрать используя gulp.

> Здравствуйте. Написал стилей, написал скриптов, собрал кое-как вебпаком.
> Локально все работает.
> Скачиваю из репозитория, устанавливаю, собираю, проверяю через папку stub - работает.
> 
> Отправляю на автотесты - не проходит. Когда еще не писал script.js и проверял автотестами вертску, в build помещал пустой script.js - всё с автотестами было ок. Причина, как я понимаю, в моем script.js. Судя по количеству пунктов в error log, я что-то делаю принципиально неправильно.
> ![Screenshot_2020-01-08 https account shri yandex](https://user-images.githubusercontent.com/50028051/71965127-216eda80-3210-11ea-84c1-c230b7e81f77.png)

Судя по ошибкам ты пытаешься слушать событие до готовности страницы. Проверь сам код js для блоков, если там ты уверен, что правильно. Смотри сборку.

**Comment by yndx-shri-reviewer** [comment]
> Причина, как я понимаю, в моем script.js.

Да. Если при отрисовке страницы в консоль браузера валятся ошибки, то мы даже не сравниваем скриншоты.

> Судя по количеству пунктов в error log, я что-то делаю принципиально неправильно.

К сожалению, мы не можем давать комментариев по правильности/неправильности реализации.

**Comment by stas-laniuk** [comment]
Понял. Закрываю.
