### ISSUE TITLE
Block "Page"

### ISSUE THREAD

**Issue by TimurGumarov** [yndx-shri-reviewer/shri-2020-task-1#58]
Добрый день!

Насколько я понимаю, в описании упустили описание блока `page`?
И насколько я понял по реализации, ему просто надо задать дефолтный цвет в  `background-color`.

**Comment by bemdev** [comment]
> И насколько я понял по реализации, ему просто надо задать дефолтный цвет в `background-color`.

Ты это выявил меняя темы? Вообще об этом нет описаний и так же неважно как будет свитчится страница, таких тестов вроде и нет. 

Поэтому это на твое усмотрение. Но инициатива **ет инициатора, будь аккуратнее.

**Comment by yndx-shri-reviewer** [comment]
Блок page был добавлен в bemjson для нашего удобства. Он не является частью дизайн-системы. Ничего ему задавать не нужно.

**Comment by TimurGumarov** [comment]
Понял, спасибо!
