### ISSUE TITLE
Смысловой блок history отступ сверху

### ISSUE THREAD

**Issue by Vorovalnitsev** [yndx-shri-reviewer/shri-2020-task-1#6]
history__show (e-accordion__short list__item_vertical-align_center list__item_indent-t_m)[контейнер для видимой части строки]

Примиксованый внешний отступ сверху(list__item_indent-t_m) не дает собрать разметку по скриншоту. Можете проверить необходимость использования данного отступа?

**Comment by yndx-shri-reviewer** [comment]
Данный отступ там необходим, и полученный результат должен соответствовать макетам.
