### ISSUE TITLE
templater.js

### ISSUE THREAD

**Issue by tensegrity666** [yndx-shri-reviewer/shri-2020-task-1#7]
Документации не предполагается?

**Comment by yndx-shri-reviewer** [comment]
Документацию добавим.
templater.js -- это код, полученный в результате вызова [bemthml.generate()](https://github.com/bem/bem-xjst/blob/master/docs/en/3-api.md#bundling), в котором дописан экспорт, чтобы его можно было собрать вебпаком и выполнить в браузере.
Если неудобно так делать, то вы можете подключить его статически, заменить экспорт на присваивание глобальной переменной, и использовать ее, где вам удобнее.
Или же вообще сделать шаблонизацию на сервере при помощи [bem-xjst](https://github.com/bem/bem-xjst).

**Comment by tensegrity666** [comment]
> Или же вообще сделать шаблонизацию на сервере при помощи [bem-xjst](https://github.com/bem/bem-xjst).

Спасибо, именно этим инструментом и воспользовался

**Comment by yndx-shri-reviewer** [comment]
Добавили в /stub небольшой проект для облегчения проверки задания.
