### ISSUE TITLE
Переменная gap

### ISSUE THREAD

**Issue by oreshkin-ay** [yndx-shri-reviewer/shri-2020-task-1#8]
День добрый! В предыдущих issues писали про gap. Тоже столкнулся с этим. При значении --gap = xl, верстка ложится в соответствии с макетами.
Пример с --gap: -xxxl; (из задания)
![image](https://user-images.githubusercontent.com/17002069/69910358-4acf6600-141b-11ea-9790-6954faf28dd2.png)
Пример с --gap: -xl;
![image](https://user-images.githubusercontent.com/17002069/69910368-6d617f00-141b-11ea-8c23-55458135b0d7.png)
Посмотрите, пожалуйста.

**Comment by playhardgopro** [comment]
А в мобильной версии --gap должен быть s

**Comment by yndx-shri-reviewer** [comment]
Да, вы правы. xl в десктопном и s в мобильном представлении. Поправили в условии. Спасибо!
