### ISSUE TITLE
Input border

### ISSUE THREAD

**Issue by MOTORIST** [yndx-shri-reviewer/shri-2020-task-1#9]
В макете input идет с рамкой. В описании блока, я этого не нашел.
[Ссылка на описание](https://github.com/yndx-shri-reviewer/shri-2020-task-1/blob/master/BASE.md#%D0%B1%D0%BB%D0%BE%D0%BA-input)

**Comment by yndx-shri-reviewer** [comment]
Ширина границ блока -- 3px. Добавили в описание. Спасибо!
